import { StackProfile } from '../types';

export const tanstackStart: StackProfile = Object.freeze({
    name: 'tanstack-start',
    folders: [
        '-components',
        '-containers',
        '-hooks',
        '-client/services',
        '-client/repositories',
        '-server/functions',
        '-server/services',
        '-server/repositories',
        '-schemas',
        '-types',
    ] as const,
    layers: [
        'page',
        'component',
        'container',
        'hook',
        'clientService',
        'clientRepository',
        'serverService',
        'serverRepository',
        'controller',
        'schema',
        'types',
    ] as const,
    layerDirs: {
        component: '-components',
        container: '-containers',
        hook: '-hooks',
        clientService: '-client/services',
        clientRepository: '-client/repositories',
        serverService: '-server/services',
        serverRepository: '-server/repositories',
        controller: '-server/functions',
        schema: '-schemas',
        types: '-types',
    },
    clientDirective: false,
    serverComponents: false,
    queryHooks: true,
});
