import { describe, it, expect } from 'vitest';
import * as path from 'path';
import { detectPackageManager, updateCommand, FsLike } from '../package-manager';

const ROOT = path.resolve(path.sep, 'work', 'app');

const fsWith = (present: Record<string, string>): FsLike => ({
    exists: (filePath) => Object.prototype.hasOwnProperty.call(present, path.basename(filePath)),
    readFile: (filePath) => {
        const name = path.basename(filePath);
        if (!(name in present)) throw new Error(`ENOENT ${filePath}`);
        return present[name];
    },
});

describe('detectPackageManager', () => {
    it('defaults to npm with no lockfile', () => {
        expect(detectPackageManager(ROOT, fsWith({ 'package.json': '{}' }))).toBe('npm');
    });

    it.each([
        [{ 'package-lock.json': '' }, 'npm'],
        [{ 'pnpm-lock.yaml': '' }, 'pnpm'],
        [{ 'bun.lock': '' }, 'bun'],
        [{ 'bun.lockb': '' }, 'bun'],
        [{ 'yarn.lock': '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n' }, 'yarn-classic'],
        [{ 'yarn.lock': '__metadata:\n  version: 8\n' }, 'yarn-berry'],
    ])('detects %o as %s', (lockfiles, expected) => {
        expect(detectPackageManager(ROOT, fsWith({ 'package.json': '{}', ...lockfiles }))).toBe(expected);
    });

    it('prefers pnpm over a stray yarn.lock when both exist', () => {
        expect(detectPackageManager(ROOT, fsWith({ 'package.json': '{}', 'pnpm-lock.yaml': '', 'yarn.lock': '' }))).toBe('pnpm');
    });

    it('lets the packageManager field win', () => {
        expect(detectPackageManager(ROOT, fsWith({ 'package.json': JSON.stringify({ packageManager: 'pnpm@9.1.0' }), 'package-lock.json': '' }))).toBe('pnpm');
        expect(detectPackageManager(ROOT, fsWith({ 'package.json': JSON.stringify({ packageManager: 'yarn@1.22.22' }) }))).toBe('yarn-classic');
        expect(detectPackageManager(ROOT, fsWith({ 'package.json': JSON.stringify({ packageManager: 'yarn@4.5.0' }) }))).toBe('yarn-berry');
        expect(detectPackageManager(ROOT, fsWith({ 'package.json': JSON.stringify({ packageManager: 'bun@1.1.0' }) }))).toBe('bun');
    });

    it('falls back to lockfiles when packageManager names something unknown', () => {
        expect(detectPackageManager(ROOT, fsWith({ 'package.json': JSON.stringify({ packageManager: 'deno@2' }), 'pnpm-lock.yaml': '' }))).toBe('pnpm');
    });
});

describe('updateCommand', () => {
    it.each([
        ['npm', 'npm install domain-driver@latest'],
        ['pnpm', 'pnpm update domain-driver@latest'],
        ['yarn-classic', 'yarn upgrade domain-driver@latest'],
        ['yarn-berry', 'yarn up domain-driver@latest'],
        ['bun', 'bun update domain-driver@latest'],
    ] as const)('local %s runs %s', (manager, display) => {
        const command = updateCommand('local', manager);
        expect(command.display).toBe(display);
        expect([command.command, ...command.args].join(' ')).toBe(display);
        expect(Object.isFrozen(command)).toBe(true);
    });

    it('global always uses npm -g', () => {
        expect(updateCommand('global', 'pnpm').display).toBe('npm install -g domain-driver@latest');
    });
});
