import { END, START } from './markers';

const AGENTS_LINES: readonly string[] = [
    START,
    '## Scaffolding with domain-driver',
    '',
    'This project uses [domain-driver](https://github.com/IsaacHatilima/domain-driver) to scaffold feature folders. Scaffold first, then fill in the generated files. Do not hand-write a layer the tool can generate.',
    '',
    '- New feature: `npx domain-driver make:feature <feature>/<Entity> -a`',
    '- One layer in an existing feature: `npx domain-driver make:<layer> <feature>/<Entity>` where layer is types, schema, repository, service, controller, component, container, or hook',
    '- Any operation that is not List, Show, Create, Update, or Delete: `npx domain-driver make:action <feature>/<Entity> <actionName>`. Add `--with-input` when it takes a request body and `--returns one|void` when it does not return a list.',
    '',
    'Rules the generated code follows, and that new code must keep:',
    '',
    '- One file per action per layer. `findActiveUsers` gets `FindActiveUsers.service.ts`, `FindActiveUsers.repository.ts`, and `FindActiveUsers.controller.ts`. It never goes inside `ShowUser.service.ts` or `ListUser.service.ts`.',
    '- Hooks are one file per action too: `<Action><Entity>.hook.ts` exporting `use<Action><Entity>` (for example `useListUser`, `useCreateUser`). There is no combined `use<Entity>.ts`.',
    '- The chain is controller or hook, then service, then repository. Business logic lives in services. Data access lives in repositories. Controllers validate input and call one service.',
    '- Feature folders are kebab-case (`coffee-type`). Entity, action, and class names are PascalCase (`CoffeeType`, `FindActiveUsers`).',
    '- Generated repositories throw until you wire them to your data source. Generated controllers on Node need a line in `<feature>.routes.ts`, and on Nest need registering in `<feature>.module.ts`; the tool prints the exact line.',
    '',
    'Full guidance: `.claude/skills/domain-driver/SKILL.md`. Re-run `npx domain-driver init` after upgrading domain-driver to refresh this section.',
    END,
];

const SKILL_LINES: readonly string[] = [
    '---',
    'name: domain-driver',
    'description: Scaffold domain-driven feature folders with the domain-driver CLI. Use when creating a feature, adding a layer (types, schema, repository, service, controller, component, container, hook) to an existing feature, or adding any operation beyond List, Show, Create, Update, and Delete.',
    '---',
    '',
    '# domain-driver',
    '',
    'Every feature lives in one folder, and every action in every layer is one file. Use the CLI to create files; write the logic inside them by hand.',
    '',
    '## Detect the stack',
    '',
    'The tool reads `package.json` and prints `Stack: <stack> (detected)` before every command. Stacks: `next-fullstack`, `next-frontend`, `react`, `node` (Express, Fastify, Hono, or none), `nest`, `tanstack-start`. Override with `--stack <name>` if detection is wrong.',
    '',
    '## Commands',
    '',
    '| Task | Command |',
    '|---|---|',
    '| New feature with every layer | `npx domain-driver make:feature users/User -a` |',
    '| New feature, folders only | `npx domain-driver make:feature users` |',
    '| Entity interface | `npx domain-driver make:types users/User` |',
    '| Create and Update schemas (and Nest DTOs) | `npx domain-driver make:schema users/User` |',
    '| Five repositories | `npx domain-driver make:repository users/User` |',
    '| Five services | `npx domain-driver make:service users/User` |',
    '| Five controllers or Next route handlers | `npx domain-driver make:controller users/User` |',
    '| A bespoke operation | `npx domain-driver make:action users/User findActiveUsers` |',
    '| Bespoke operation with a request body | `npx domain-driver make:action users/User archiveUser --with-input --returns one` |',
    '| Component, container, hook | `npx domain-driver make:component users/UserCard`, `make:container users/UserContainer`, `make:hook users/User` |',
    '| Refresh this guidance | `npx domain-driver init` |',
    '',
    'On `next-fullstack` and `tanstack-start`, `make:service` and `make:repository` take `--side client|server|both` (default both).',
    '',
    'Hooks are one file per action — `<Action><Entity>.hook.ts` exporting `use<Action><Entity>` — never a combined `use<Entity>.ts`. On `tanstack-start` they are TanStack Query hooks backed by a generated `<feature>.keys.ts`; elsewhere they are plain React state.',
    '',
    '## Rules',
    '',
    '1. **Scaffold before writing.** If a file the tool can generate does not exist yet, generate it. Do not create `services/FindActiveUsers.service.ts` by hand.',
    '2. **One action, one file, every layer.** A new operation is a `make:action`, never a new method on an existing action class and never a branch inside Show or List.',
    '3. **Keep the chain.** Controller or hook calls one service. Service calls one repository. Repositories do data access only.',
    '4. **Names.** Feature folders kebab-case. Entities, actions, and classes PascalCase. Action names include their noun: `archiveUser`, `findActiveUsers`.',
    '5. **Do not widen the standard five.** List returns all, Show returns one by id, Create takes the create schema, Update takes id and the update schema, Delete takes id. Anything else is a bespoke action.',
    '6. **Finish what the tool leaves open.** Fill the `TODO` in each repository. Add the printed line to `<feature>.routes.ts` on Node or register the printed classes in `<feature>.module.ts` on Nest. Add fields to the Zod schemas.',
    '',
    '## Layout by stack',
    '',
    '- Next.js: `app/<feature>` or `src/app/<feature>`; route handlers under `app/api/<feature>`.',
    '- React and Node: `src/features/<feature>` or `features/<feature>`.',
    '- Nest: `src/<feature>` with a `<feature>.module.ts`.',
    '- TanStack Start: `src/routes/<feature>` or `routes/<feature>`; every layer folder is prefixed with `-` so the router ignores it, and the entry file is `index.tsx`, not `page.tsx`.',
];

export const AGENTS_SECTION: string = AGENTS_LINES.join('\n');
export const SKILL_CONTENT: string = `${SKILL_LINES.join('\n')}\n`;
